############################################################
# Dockerfile to build hello-world test
# Based on docker.io/eboraas/apache-php
############################################################

# Set the base image
FROM docker.io/php:5.5.32-apache

# File Author / Maintainer
MAINTAINER Lawson 994008461@qq.com

# Locale source file
# COPY config/php.ini /usr/local/etc/php
COPY src/ /var/www/html

# No CMD
